### ISSUE TITLE
Automatically "restoring" new window instances to random locations/sizes

### ISSUE THREAD

**Issue by ScorelessPine** [kangyu-california/PersistentWindows#388]
Prior to updating, I never had this issue, but as of now, I've noticed that the program keeps "restoring" a few certain windows to seemingly random locations, including new ones like the file download location prompt from Firefox. It shows up in its existing location, as it is supposed to, and then a second later, PersistentWindows grabs and moves the download window to another location, sometimes on another screen, even resizing the window to be quite small in one instance.

The attached video here is a small example of some of the odd behavior I've been seeing, and this behavior does not happen when the program is closed, so I'm pretty sure it's the cause. The very first download window in the attached video, however, is the behavior I saw most often early on when I was considering making this issue, but after attempting to record it multiple times, that was the only instance I could get of it happening.

https://github.com/user-attachments/assets/93cddc4b-9cff-4a02-9622-98c21d23db56

**Comment by ScorelessPine** [comment]
I have a guess this may be caused by -capture_floating_window, however despite setting it to 0 with command line arguments it still seems to occur. This behavior sounds similar to what JonnyTsGitHub described in his last message in #352

**Comment by kangyu-california** [comment]
The issue is similar to #369,

You may want to run PW without previous memory by 1. exit PW, 2. delete C:\Users\\[user]\AppData\Local\PersistentWindows\window_pos.xml, 3. restart PW

If that does not work, you may run PW with -auto_restore_new_window_to_last_capture=0 to disable the new feature in 5.60

**Comment by ScorelessPine** [comment]
That suggestion of deleting previous memory seems to work until the program is restarted again, then the behavior continues. I assume that's because it creates another window_pos.xml on closing.

**Comment by kangyu-california** [comment]
I ran into the same problem during developing the new feature.

I thought the issue is fixed 5.60 as it runs fine on my PCs, not sure why it doesn't work for a few users.

**Comment by montoner0** [comment]
The feature seems incorrectly detects active monitor and resizes windows as if they are on a smaller screen

**Comment by Stepan-H** [comment]
Same problem. When I work with MS Access, there are MDI forms. Suddenly, during editing form, it disappears under hands... Previous version 5.59 didn't do this.

**Comment by skhalid93** [comment]
Have the same problem. Once I updated, windows are opening up in random locations and random sizes. Prior to the update, absolutely no issues.

**Comment by shimaowo** [comment]
Same issue as of the update - windows end up at random tiny sizes at random locations on random monitors. Sometimes they even end up offscreen from both my monitors, and I can't 'fix' that until I disable PW. It worked fine before the update.

**Comment by kangyu-california** [comment]
Please try 5.61 (pre-release)

**Comment by ScorelessPine** [comment]
Installed 5.6.1 and re-enabled the auto_restore_new_window_to_last_capture option and initially I'm not seeing the issue in my previous test cases anymore, I'll update you if it happens again though, but for now it seems good to me.

**Comment by the-real-vortex-v** [comment]
Were do I get the Pre-Release?

**Comment by kangyu-california** [comment]
> Were do I get the Pre-Release?

https://github.com/kangyu-california/PersistentWindows/releases/tag/5.61

**Comment by mateuszkozakiewicz** [comment]
> Please try 5.61 (pre-release)

It did not help in my case, I deleted `window_pos.xml` after updating but it made no difference.
It happens randomly except when window is maximized, then it will always end up in a random location on one of my screens.

So far I can reproduce it like this 100% of the time:
1. open windows explorer
2. maximize the window
3. close it
4. open again
5. it jumps to a random location

but I noticed there are more event which trigger window jumping for example when window tries to resize itself.

https://github.com/user-attachments/assets/a9bfe801-11c5-41ff-8601-196322e0aae1

**Comment by montoner0** [comment]
I'm randomly getting this issue even with 
`-auto_restore_new_window_to_last_capture=0 -auto_restore_existing_window_to_last_capture=0`

**Comment by kangyu-california** [comment]
@mateuszkozakiewicz After maximize a window, do not kill it immediately, please wait 3 seconds or more to allow PW to capture it. Similarly after launching a new maximized window, please wait 5 seconds or more before shifting focus to other window. I will continue looking into optimizing the required delay, but it doesn't sound like a serious issue for typical user.

**Comment by kangyu-california** [comment]
@montoner0 Could you please make a short video to demonstrate what happens exactly?

**Comment by shimaowo** [comment]
> fwiw, this only STARTED to happen here with 5.61 patch1

This is incorrect. This bug was filed before that release existed.

**Comment by montoner0** [comment]
> [@montoner0](https://github.com/montoner0) Could you please make a short video to demonstrate what happens exactly?

Sorry, wasn't able to reproduce. It had happened a couple of time on 5.60 and hasn't happened on 5.61.

**Comment by jpotelle** [comment]
Windows 10 22h2 build 19045.5487
I am using PW 5.61.9198.30237 and this is still happening. e.g. [jEdit](https://jedit.org/) child windows (such as opening Options, or opening a new View window) are moved even though there is no monitor disconnect event to fix. I typically do not manually store a snapshot, I just let PW do it's thing.

**Comment by unacceptablet** [comment]
> 5.62 turned off the feature by default

Even though it has a few problems, this feature is incredibly useful and should not be disabled by default IMO.
Of course the best thing would be when a fix is available.

**Comment by kangyu-california** [comment]
5.63 pre-release is out with -auto_restore_new_window_to_last_capture enabled again. Thanks for trying out.

**Comment by kangyu-california** [comment]
5.64 should be much better

**Comment by kangyu-california** [comment]
@jpotelle jEdit issue should have been fixed in 5.65

@Stepan-H I don't have Office Access for testing, if 5.65 still does not work, the only option is turn off the auto restore feature.

**Comment by libove** [comment]
I believe that I am still seeing this issue on 5.65. I sometimes randomly find on logging back in to a Windows session that some window or another has been resized to "very small"; I occasionally see a new window opened up and then abruptly change size and position a bit. I have tried deleting window_pos.xml, but that did not make a difference.

**Comment by kangyu-california** [comment]
@libove @neurocline 
In PW 5.65 newly opened dialog windows (such as Property windows which are non-resizable) are excluded from auto restore, this is true even without -auto_restore_new_window_to_last_capture=0 on command line. Please double check your PW version because auto-upgrade on Win11 could fail.

I have further disabled auto-inheritance of dialog windows, please try [PersistentWindows5.65_patch3.zip](https://github.com/user-attachments/files/20428599/PersistentWindows5.65_patch3.zip)

@neurocline
For backbone-feature-only users, the suggestion is to freeze PW version upgrade, this can be done by selecting menu "Disable upgrade check", or using command line -check_upgrade=0

**Comment by libove** [comment]
Confirmed, this is 5.65 on this system, exhibiting the "Window/dialog opens then moves/resizes" behavior. Including after removing window_pos.xml and restarting.

**Comment by libove** [comment]
Hm, ok, I think I've seen it again. I just unlocked a logged-in Windows session, and the window for an application "PureVPN" was placed partly off the right edge of the screen. I didn't do that; that shouldn't have ever been a recorded location for the window.
Forgive me, I'm not thinking clearly - is there/ where is a log created by PersistentWindows to record how it noticed the window and what if any decision PersistentWindows made about (re-)positioning that window?
thank you,

**Comment by kangyu-california** [comment]
@libove 
PW support event logging for windows of specific processes using command line option -debug_process
-debug_process "PureVPN.exe"
If PW does not restore specific window, chances are PW was not run in admin mode, or that application actively repositions itself, disregarding PW restore.

**Comment by libove** [comment]
Okay, the issue happened again, with -debug_process enabled. Um, where is the log file? 😅
Thank you,

**Comment by libove** [comment]
Um. Also. Confirmed, vesion 5.65, on a different system; I just restarted Chrome for a routine Google update, and when Chrome restarted (I keep at least two Chrome Profiles running, in at least two Chrome windows) one of the Chome windows opened (or very quickly resized) to .. a shape I would never set a browser window to (roughly 450 x 600) and which is patently different from the size that all of the Chrome windows had just prior to the restart.

**Comment by kangyu-california** [comment]
5.66 further improves accuracy of new window matching to killed one, especially for Java programs like jEdit.

@libove the log2.zip shows new ToDo window is incorrectly matched to another Microsoft store app (Realtek sound control), however I could not reproduce the issue, please consider uninstall the latter.

**Comment by libove** [comment]
Ouch. Does that suggest that many/all Windows Store apps will have un-correctly-matchable window names? That could be a serious problem as, despite all our efforts to avoid actually ever using anything from the Microshaft store, we gradually are forced to accept more and more "Modern" (gulp 🤮) app(lications! dammit! they are appLICATIONS, not APPs!) on our systems :-/

> 5.66 further improves accuracy of new window matching to killed one, especially for Java programs like jEdit.
> 
> [@libove](https://github.com/libove) the log2.zip shows new ToDo window is incorrectly matched to another Microsoft store app (Realtek sound control), however I could not reproduce the issue, please consider uninstall the latter.

**Comment by libove** [comment]
Um. I updated to 5.66. A few hours later, a new Chrome window (Chrome was already running, and from one open Chrome profile, I clicked the Chrome menu to open a new Chrome windows in another of my Chrome profiles) opened up very small .... (to my recollection, no recent Chrome window had been that size/shape/position).

**Comment by libove** [comment]
I also notice that Outlook (Classic) Calendar entry windows and Contact windows seem to get snagged by PersistentWindows. I'll double-click to create a new Calendar entry, or I'll double-click on a Contact to open it up into its own Window, and momentarily after the window appears wherever Outlook and the Windows window manager would have placed it, it is abruptly relocated and sometimes resized (by PersistentWindows I presume). I think that emergent windows from Outlook maybe should be exempted from PW?

**Comment by libove** [comment]
Further observation on the current interaction between PW (5.66) and Outlook. I exited Outlook normally (had had a nearly-full-screen window open set to Mail, another nearly-full-screen window open set to Contacts, and another nearly-full-screen window open set to Calendar, plus the small window showing fired-but-not-yet-dismissed calendar events). When I re-started Outlook after leaving it to fully close for about ten seconds, the main Outlook window opened nearly-full-screen as before but almost immediately was re-sized (by PW I assume) to a window taking up only about 2/3 of the screen (both horizontally and vertically).
Can PW distinguish various windows open in one Outlook.EXE program and remember them individually? I think that it used to, or perhaps simply it didn't change Outlook re-opening windows' sizes until a more recent PW version, because I don't remember this happening until recently.

**Comment by kangyu-california** [comment]
@libove Could not reproduce any case you reported unfortunately, it would be nice if you can provide a video capture of your screen like in #406 (using software such as Obs Studio)

**Comment by libove** [comment]
Weirdly, I don't think I've noticed it happening recently. If I do see it again, I'll try to reproduce it while screen capturing.
