### ISSUE TITLE
MSI Afterburner and Winamp get thrown back on main monitor

### ISSUE THREAD

**Issue by GloriousGloryGG** [kangyu-california/PersistentWindows#89]
![before](https://user-images.githubusercontent.com/79727746/109366027-01f1a180-7858-11eb-9345-de7cff77eb84.jpg)
![after](https://user-images.githubusercontent.com/79727746/109366033-061dbf00-7858-11eb-80e7-faba8d1f233b.jpg)

**Comment by GloriousGloryGG** [comment]
Note that this only appears to happen when afterburner is minimized in the system tray.  However, that is usually where it is resting.

**Comment by ldfuller01** [comment]
There seems to be an issue with system-tray-minimized apps in general. When PW 5.17 activates after waking up monitors, my Discord, Slack, and Dropbox (or some combination of the three) appear on the screen as unresponsive windows even if they were previously minimized to taskbar or system tray, and they are restored to normal when I go to system tray and open the apps from there. I went back to PW 5.10 until a new update comes around.

**Comment by kangyu-california** [comment]
@GloriousGloryGG 
Please try release 5.18, MSI Afterburner should be working fine now.
I dont have the same issue with Winamp on my PC.

@ldfuller01 
 I didn't get a chance to test Discord/Slack/Dropbox, please test release 5.18 (which fixed a bug due to recognizing minimized window as off-screen and try to automatically fix its location)

**Comment by GloriousGloryGG** [comment]
> @GloriousGloryGG
> Please try release 5.18, MSI Afterburner should be working fine now.
> Winamp seems to move by itself sometimes, the move is not caused/controlled by PW.
> 

Hi kangyu,

Thanks for the quick response.  Unfortunately the same issue is present.  If MSI Afterburner is minimized and the screens power of, upon powering on and re-opening the program, it relocates on the main screen as such.

![afterburner](https://user-images.githubusercontent.com/79727746/109459895-4c744900-7a25-11eb-88a5-51e8b68f7169.jpg)

**Comment by ldfuller01** [comment]
> @GloriousGloryGG
> Please try release 5.18, MSI Afterburner should be working fine now.
> Winamp seems to move by itself sometimes, the move is not caused/controlled by PW.
> 
> @ldfuller01
> I didn't get a chance to test Discord/Slack/Dropbox, please test release 5.18 (which fixed a bug due to recognizing minimized window as off-screen and try to automatically fix its location)

I've been testing 5.18 for the last 3 days to give it a few chances; I also rebooted my computer once during those days, in case that means anything. Unfortunately Discord and Slack are still experiencing the same issue; Dropbox has not, but I also haven't opened its window lately (I usually just save to its folder in File Explorer).

I regret not screenshotting it, but when Discord is last on my second monitor and then is minimized to system tray (via "closing" with the red X), and when it pops up as a ghost window after I wake the monitors, the Discord window will span across the border between the screens; the actual content dimensions of the application are as if PW restored it, but some large black bars appear on the right and bottom of the window. When I select Discord from system tray to fix it, the application content then fills these bars so that the window is oversized. (That last part probably has a lot to do with my display scaling; I have a 4k monitor (secondary) next to a 1440p monitor (primary); the 4k is scaled to 175% and the 1440p is scaled to 125%.)

**Comment by kangyu-california** [comment]
@GloriousGloryGG

MSI Afterburner should work fine now in release 5.19

**Comment by kangyu-california** [comment]
@ldfuller01

I don't have a similar monitor setup to reproduce the scaling issue.

There is a PW command line option to try, -redraw_desktop

Note that PW is only responsible for restore window to prior location and size, ultimately it is up the the Skype/Discord app to refresh the content of window with respect to display scaling.

**Comment by GloriousGloryGG** [comment]
Hi Kangyu, even on the latest version this issue is still persistent with MSI.

I can reproduce it every time by moving msi to the second monitor, minimizing it, and then turning off my second monitor and turn it back on.  MSI when restored goes to screen 1

**Comment by kangyu-california** [comment]
MSI Burner window is a special one which requires more time to capture.
Try this procedure instead,

move MSI window
wait for 3~4 seconds
minimize it
...
